### ISSUE TITLE
Warning: crossOriginIsolated is null, browser might not support buffer sharing.

### ISSUE THREAD

**Issue by wgtun** [Desdaemon/flutter_rust_bridge_template#47]
When I publish web app to nginx server, I get this warning, and rust function no run correctly

**Comment by Desdaemon** [comment]
Assuming you have already [added the required headers](https://cjycode.com/flutter_rust_bridge/build_wasm.html#setting-up-the-web-server), it could be some quirks with Firefox that disallow buffer sharing. Try configuring nginx so that you can inspect `crossOriginIsolated` in your web browser and have it be true.

**Comment by wgtun** [comment]
> Try configuring nginx so that you can inspect `crossOriginIsolated` in your web browser and have it be true

thanks,I have already  added the required headers , I found the rust String buffer can't return,  let me try enable crossOriginIsolated
